# Generated by Django 5.2.3 on 2025-09-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lead_type', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('close_win', 'Close Win'), ('close_loss', 'Close Loss'), ('not_interested', 'Not Interested')], max_length=32)),
                ('service_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='service', max_length=16)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=8)),
                ('caller_id', models.CharField(blank=True, help_text='Twilio number (E.164 format) or leave blank to use default.', max_length=32, null=True)),
                ('retry_attempts', models.PositiveSmallIntegerField(default=2)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('recurring', 'Recurring')], default='immediate', max_length=16)),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True)),
                ('recurrence_interval_minutes', models.PositiveIntegerField(blank=True, help_text='If recurring: interval in minutes (e.g., 1440 for daily).', null=True)),
                ('recommendation_enabled', models.BooleanField(default=False)),
                ('upsell_text', models.TextField(blank=True)),
                ('crosssell_text', models.TextField(blank=True)),
                ('fallback_whatsapp', models.BooleanField(default=False)),
                ('fallback_email', models.BooleanField(default=False)),
                ('fallback_voicemail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=8)),
                ('tts_voice', models.CharField(blank=True, help_text="Optional TTS voice identifier supported by Twilio (e.g., 'alice').", max_length=128, null=True)),
                ('voice_script', models.TextField(help_text='Script content. Use placeholders like [Name], [Product].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('no_answer', 'No Answer')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('twilio_sid', models.CharField(blank=True, max_length=128, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='ai_calling.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ai_calling.voicetemplate'),
        ),
    ]
