# Generated by Django 5.2.7 on 2025-10-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Close Win', 'Close Win'), ('Close Loss', 'Close Loss'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('service_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('subscription', models.CharField(blank=True, max_length=50, null=True)),
                ('complementary_items', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('past_purchases', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_automation.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsell_item', models.CharField(blank=True, max_length=100, null=True)),
                ('cross_sell_item', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_automation.lead')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_automation.serviceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_automation.lead')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_automation.recommendation')),
            ],
        ),
    ]
