# Generated by Django 5.2 on 2025-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_automation', '0002_fix_recommendation_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='leadinteraction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leadinteraction',
            name='past_purchases',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendationoutcome',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='recommendationoutcome',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='complementary_items',
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendationoutcome',
            name='outcome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='category',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
