# Generated by Django 5.2 on 2025-10-12 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_automation', '0003_remove_lead_created_at_remove_lead_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recommendationoutcome',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendationoutcome',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
